### ISSUE TITLE
Can I make "close/remove/clear" button?

### ISSUE THREAD

**Issue by NeedHate** [scottcheng/cropit#146]
For example, user chooses the picture, it appears, but he wants another one. When the picture appears also appears the "X" close button to remove it. He removes it. But when he clicks on label (which is for file input, and its on "cropit-image-preview" positioned as absolute ) the picture doesnt refreshes in IE, Chrome, but FF is fine.  I use this code: 
$('.image-editor-cancel').click(function(){
		if($('.cropit-image-preview').hasClass('cropit-image-loaded')){
		$('.cropit-image-preview').removeClass('cropit-image-loaded').removeAttr('style');
	}
})
So the question is why its not refreshing the picture?

**Comment by sidaurukfreddy** [comment]
hi there i have been solved this issue, please go <a href="http://stackoverflow.com/questions/34310925/remove-or-clear-background-image-urlimage-png-after-success-submit-in-modal-b">Here</a> give your vote there lah 
<pre>
$('.cropit-image-preview').css('background-image', ''); //remove preview-images
$('.cropit-image-background').removeAttr('src'); //remove background images
</pre>

**Comment by NeedHate** [comment]
sidaurukfreddy, hello! Sorry for the late answer. You  idea doesnt solve my issue. See the code on [link to codepen](http://codepen.io/NeedHate/pen/XXKdvz) to see the issue itself. 
According to this issue: after "Cancel button" have been pressed the background is removed but I cant select a new picture again. But this issue is ok in FF.

**Comment by sidaurukfreddy** [comment]
Hello you need to add <pre>  event.preventDefault();</pre>
please check this <a href="http://codepen.io/sidaurukfreddy/pen/pgbbad">Out</a>

and did you know how to handle multiple images with diffrent width and height ? this is the last hard issue for me,

**Comment by deronsizemore** [comment]
I tried this out and it mostly works but it doesn't seem to allow the re-adding of an image once the initial image is deleted? If you go to the example that @sidaurukfreddy gave at CodePen, you can load an image and delete it, but if you click to load an image again, it does not load back into the cropit area; it just stays blank.

Any ideas on that?

**Comment by safarjaisur** [comment]
Hi guys , 
I  am also facing this issue. **I am removing image from editor at step 3**, I have an image gallery and file upload function. Whenever user pick any pics from library  at that time I needs to clear image editor then it is not  work properly. May it's help full to you guys.below Mention code is  work  fine  with  me  : 

**Step  1 Html Setup & CSS **   

<div class="image-editor">              
                  <div class="cropit-preview"></div>                  
                  <div class="button-group ">
                 
                  <input type="file"  name="browseFile" id="browseFile" class="cropit-image-input">
                  <div class="image-size-label">Resize image</div>
                  <input type="range" name="range" class="cropit-image-zoom-input">        
                  <input type="hidden" name="image-data" class="hidden-image-data" />

                  <a href="javascript:void(0);" title="Upload" class="btn orange-btn upload-btn">Browse Image</a>
                  <p>It must be an image file. <br>.png, .jpg, .jpeg, .gif, .bmp</p>
                </div>
              </div>
**CSS** 
`
<style>
.cropit-preview {
        background-color: #f8f8f8;
        background-size: cover;
        border: 1px solid #ccc;
        border-radius: 3px;
        margin-top: 7px;
        width: 400px!important;
        height: 400px!important;
      }
   .cropit-preview-image-container {
        cursor: move;
      }
      .cropit-preview-image-container > img{
          max-width:none !important;          

      }
</style>
`
**Step 2 Cropit Initialization**  

//Sdet Image  Cropping Tool  
 $('.image-editor').cropit(
 {
    "smallImage":"reject",
     "onImageErrorfunction": function (fileObj){
        custom_message(fileObjError.message);
    },
    "onImageError":function(fileObjError) {
        custom_message(fileObjError.message);
        
    },
    "onImageLoadedfunction":function(fileObject){
      console.log(fileObject);

    },
    "onOffsetChange":function(fileOffsetObj){
      console.log("offset Change "+fileOffsetObj);
      var imageUrl = $('.image-editor').cropit('export');
      $('.campFile1,#campFile').attr('src',imageUrl);

    }
 }); 

**Step 3 : Clean uo  Image  Editor**

$('input.cropit-image-input').val('');
$('.cropit-preview').removeClass('cropit-image-loaded');
$('.cropit-preview-image').removeAttr('style');
$('.cropit-preview-image').attr('src','');
